Updated NewPage()
Streamers-Workshop/Trovo.js pull request #18
Opened 2020-10-21 22:48 UTC by Butterstick822

Trying this again, not sure what watchdog has against me.....  Added the ability to override permission for Trovo.live accepting notifications by default. and getting rid of the unnecessary about: blank page.   -

2020-10-21 22:59 UTC, Butterstick822 reviewed
fixed spacing

2020-10-22 01:12 UTC, Bioblaze approved these changes

2020-10-22 01:13 UTC, Bioblaze requested changes
Can you edit the package.json and move the version 1 minor up? :X Since I will deploy this directly too NPM and such.

2020-10-24 01:23 UTC, Bioblaze approved these changes

2020-10-24 01:23 UTC, merged